app/urls.py
from django.urls import path 
from . import views 

app_name = 'app' 
urlpatterns = [
    path('', views.index, name='index'), 
    path('inicio/', views.inicio, name='inicio'),
    path('inicioPost',views.inicioPost, name='inicioPost'),
    path('salir',views.salir, name='salir'),
    path('inicioError/', views.inicioError, name='inicioError'),
    path('menuDecano/', views.menuDecano, name='menuDecano'),
    path('agregarEstudiante/', views.agregarEstudiante, name='agregarEstudiante'),
    path('registroPost/',views.registroPost,name='registroPost'),
    path('agregarEstudianteError/', views.agregarEstudianteError, name='agregarEstudianteError'),
    path('crearVotacion/', views.crearVotacion, name='crearVotacion'),
    path('votacionPost/', views.votacionPost, name='votacionPost'),
    path('listaDeEstudiantes/', views.listaDeEstudiantes, name='listaDeEstudiantes'),
    path('listaDeVotaciones/', views.listaDeVotaciones, name='listaDeVotaciones'),
    path('editarVotaciones/<int:id_votacion>', views.editarVotaciones, name='editarVotaciones'),
    path('editarVotacionesPost/<int:id_votacion>/', views.editarVotacionesPost, name='editarVotacionesPost'),
    path('vistaVotacionFacultad/', views.vistaVotacionFacultad, name='vistaVotacionFacultad'),
    path('vistaVotacionFacultadPost/<int:id_votacion>/', views.vistaVotacionFacultadPost, name='vistaVotacionFacultadPost'),
    path('vistaVotacionSemestre/', views.vistaVotacionSemestre, name='vistaVotacionSemestre'),
    path('vistaVotacionSemestrePost/<int:id_votacion>/', views.vistaVotacionSemestrePost, name='vistaVotacionSemestrePost'),
    path('postulacionEstudiante2/', views.postulacionEstudiante2, name='postulacionEstudiante2'),
    # estudiante
    path('detallesHistorico/',views.detallesHistorico, name='detallesHistorico'),
    path('detallesResultado/',views.detallesResultado, name='detallesResultado'),
    path('detallesResultadosFacultad/',views.detallesResultadosFacultad, name='detallesResultadosFacultad'),
    path('historicoVotaciones/',views.historicoVotaciones, name='historicoVotaciones'),
    path('listaResultados/',views.listaResultados, name='listaResultados'),
    path('listaVotacionesEstudiantes/',views.listaVotacionesEstudiantes, name='listaVotacionesEstudiantes'),
    path('postularme/',views.postularme, name='postularme'),
    path('menuEstudiante/',views.menuEstudiante, name='menuEstudiante'),
    path('postulacionExitosa/',views.postulacionExitosa, name='postulacionExitosa'),
    path('postulacion/<int:id_votacion>/',views.postulacion, name='postulacion'),
    path('postulacionPost/<int:id_votacion>/',views.postulacionPost, name='postulacionPost'),
    path('votacionExitosa/',views.votacionExitosa, name='votacionExitosa'),
    path('votacionExitosaPost/<int:id_candidato>/',views.votacionExitosaPost, name='votacionExitosaPost'),
    path('votarCandidato/',views.votarCandidato, name='votarCandidato'),
    path('votarCandidatoPost/<int:id_votacion>/',views.votarCandidatoPost, name='votarCandidatoPost'),
    path('YaEstaPostulado/',views.YaEstaPostulado, name='YaEstaPostulado'),

]

votosusta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/templates/app/agregarEstudianteError.html
{% extends "app/base.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'app/css/error.css' %}" />
{% endblock%}
    
{% block contenido%} 

        <div class="contenido">
            <div class="imagenError">
                <img src="../../static/app/img/error.png" alt="error" class="error"></a>
            </div>
            <h1>El estudiante ya se encuentra registrado</h1>
            <div class="botones">
                <a href="{% url 'app:agregarEstudiante' %}"><button class="agregar">Crear Estudiante</button></a>
                <a href="{% url 'app:listaDeEstudiantes' %}"><button class="lista">Lista de Estudiantes</button></a>
            </div>
        </div>
{% endblock %}

app/templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Votaciones USTA</title>
    <link rel="stylesheet" href="{% static 'app/css/base.css' %}" />

    {% block css%} 
    {% endblock%} 
    
    <!-- ICONOS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
    <div class="contenedor">
        <div class="header">
            <button><i class="fa-solid fa-bars"></i></button>
            <img src="../../static/app/img/Logotipo_USTA_Colombia.gif" alt="logo" class="LogoUSTA"></a>
            <h1>VOTACIONES USTA</h1>
            <!--nav crea enlaces de navegaciòn -->
            <nav class="menu">
                <ul>
                    {%if request.user.is_authenticated %}
                    <li>{{request.user.first_name}} -</li>
                    {%else%}
                    <li>Anonimo</li>
                    {%endif%}
                    <li><a href="{% url 'app:menuDecano' %}">Inicio</a></li>
                    <li><a href="{% url 'app:salir' %}">Salir</a></li>
                </ul>
            </nav>
        </div> 
        <div class="opciones">
            <nav class="menu2">
                <ul>
                    <h2>MENU</h2>
                    <li><a href="{%url 'app:agregarEstudiante'%}">Crear Estudiante</a></li>
                    <li><a href="{%url 'app:crearVotacion'%}">Crear Votación</a></li>
                    <li><a href="{%url 'app:listaDeEstudiantes'%}">Lista de Estudiantes</a></li>
                    <li><a href="{%url 'app:listaDeVotaciones'%}">Lista de votaciones</a></li>
                </ul>
            </nav>
        </div>
        {% block contenido%}
        {% endblock %}
</body>
</html>

app/templates/app/crearVotacion.html
{% extends "app/base.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'app/css/formulario.css' %}" />
{% endblock%} 

{% block contenido%} 
<div class="contenido">
    <div class="titulo">
        <h1>Crear votación</h1>
    </div>
    <div class="panel">
        <div class="formulario">
            <form action="{%url 'app:votacionPost'%}" method="POST">
                {% csrf_token %} 
                <h3>Nombre<input type="text" name="nombre"></h3>
                <h3>Fecha de inicio<input type="date" name="fechaInicio"></h3>
                <h3>Fecha de finalización<input type="date" name="fechaFin"></h3>
                {%if request.user.is_authenticated %}
                <h3>Facultad <label>{{ Facultad }}</label></h3>
                {%else%}
                <h3>Facultad <label>Anonimo</label></h3>
                {%endif%}

                <h3>Tipo de Votación 
                    <select name="tipo" id="tipo">
                        {% for t in tipo%}
                        <option value="{{t.id}}">{{t.nombre}}</option>>
                        {%endfor%}  
                    </select>
                </h3>

                <h3>Ciclo
                    <select size="1" multiple >
                        <option value="1">2022-1</option>
                        <option value="2">2022-2</option>
                    </select>
                </h3>
                <h3>Estado<label id="postulacionLabel">{{estado}}</label></h3>
                <!-- <h3>
                    <input type="radio" name="x">Postulación</label>
                    <br>
                    <input type="radio" name="x" disabled>Votación</label>
                    <br>
                    <input type="radio" name="x" disabled>Cerrado</label>
                </h3> -->
                <button id="botonCrearVotacion">Guardar</button>
            </form>
        </div>
    </div>
</div>
{% endblock%} 

app/templates/app/editarVotacion.html
{% extends "app/base.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/formulario.css' %}" />
{% endblock%} 

{% block contenido%} 
<div class="contenido">
    <div class="titulo">
        <h1>Cambiar Estado</h1>
    </div>
    <div class="panel">
        <div class="formulario">
            <h3>Nombre <Label>Votación #1</Label></h3>
            <h3>Fecha de inicio <label> 10/02/2022</label></h3>
            <h3>Fecha de finalización <label>10/03/2022</label></h3>
            <h3>Ciclo <label>2022-1</label></h3>
            <h3>Facultad <label>Ingeniería de Telecomunicaciones</label></h3>
            <h3>Tipo de Votación <label>Representante por semestre</label></h3>                    
            <h3>
                <input type="radio" name="x">Postulación</label>
                <br>
                <input type="radio" name="x">Votación</label>
                <br>
                <input type="radio" name="x">Cerrado</label>
                <br>
            </h3>
            <a href="{% url 'app:listaDeVotaciones'%}">
                <button>Guardar</button>
            </a>
        </div>
    </div>
</div>  
{% endblock%} 

app/templates/app/editarVotaciones.html
{% extends "app/base.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/formulario.css' %}" />
{% endblock%} 

{% block contenido%} 
<div class="contenido">
    <div class="titulo">
        <h1>Cambiar Estado</h1>
    </div>
    <div class="panel">
        
        <div class="formulario">
            <form action="{% url 'app:editarVotacionesPost' id %}" method="POST">
                {% csrf_token %} 
                <h3>Nombre <Label>{{v.nombre}}</Label></h3>
                <h3>Fecha de inicio <label>{{v.fechaInicio}}</label></h3>
                <h3>Fecha de finalización <label>{{v.fechaFinal}}</label></h3>
                <h3>Ciclo <label>CICLO</label></h3>
                <h3>Facultad <label>{{f}}</label></h3>
                      
                <h3>Tipo de Votación 
                    <select name="estado" id="estado">
                        {% for e in estado %}
                        <option value="{{e.id}}">{{e.nombre}}</option>
                        {%endfor%}  
                    </select>
              
                </h3>                    
                <button>Guardar</button>
               
            </form>
        </div>
        
        
    </div>
</div>  
{% endblock%} 

app/templates/app/headerEstudiante.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Votaciones USTA</title>
    <link rel="stylesheet" href="{% static 'app/css/headerEstudiante.css' %}" />
    {% block css%}
    {% endblock%}

    <!-- ICONOS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<body>
    <div class="contenedor">
        <div class="header">
            <button><i class="fa-solid fa-bars"></i></button>
            <img src="../../static/app/img/Logotipo_USTA_Colombia.gif"  alt="logo" class="LogoUSTA"></a>
            <h1>VOTACIONES USTA</h1>
            <nav class="menu">
                <ul>
                    <li><a href="{% url 'app:menuEstudiante'%}">Inicio</a></li>
                    <li><a href="{% url 'app:salir' %}">Salir</a></li>
                </ul>
            </nav>
        </div>
        <div class="opciones">
            <nav class="menu2">
                <ul>
                    <h2>MENU</h2>
                    <li><a href="{% url 'app:listaVotacionesEstudiantes'%}">Lista de Votaciones</a></li>
                    <li><a href="{% url 'app:postularme'%}">Postularme</a></li>
                    <li><a href="{% url 'app:listaResultados'%}">Lista de Resultados</a></li>
                    <li><a href="{% url 'app:historicoVotaciones'%}">Historico de votaciones</a></li>
                </ul>
            </nav>
        </div>
        {% block contenido%}
        {% endblock %}

</body>
</html>

app/templates/app/historicoVotaciones.html
{% extends "app/headerEstudiante.html" %}
{% load static %}

{% block css%}   
<link rel="stylesheet" href="{% static 'app/css/histVotaciones.css' %}" />
{% endblock%} 

{% block contenido%} 
        <div class="contenido">
             <h1>Historico de Votaciones</h1>
             <p>En este listado podrá visualizar la elección realizada en todas las votaciones finalizadas o en votación</p>
             <div class="tabla">
                <table>
                    <tr class="TitulosTabla">
                        <td>Nombre</td>
                        <td>Tipo</td>
                        <td>Fecha de inicio</td>
                        <td>Fecha de finalización</td>
                        <td>Ciclo</td>
                        <td>Ver mi voto</td>
                    </tr>
                    <tr class="ContenidoTabla">
                       <td>Nombre 1</td>
                       <td>Facultad</td>
                       <td>10/10/10</td>
                       <td>10/10/10</td>
                       <td>2022-1</td>
                       <td>
                           <a href="{%url 'app:detallesHistorico'%}">
                            <i class="fa-solid fa-eye"></i>
                           </a>
                       </td>
                   </tr>
                   
                </table>    
             </div>
        </div> 
    </div>
    
{% endblock%} 

app/templates/app/listaDeVotaciones.html
{% extends "app/base.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'app/css/tabla.css' %}" />
{% endblock%} 

{% block contenido%} 
<div class="contenido">
    <h1>Lista de Votaciones</h1>
    <div class="panel">
        <table>
            <tr  class="titulosTablas">
                <td>Nombre</td>
                <td>Tipo</td>
                <td>Fecha de inicio</td>
                <td>Fecha de finalización</td>
                <td>Ciclo</td>
                <td>Estado</td>
                <td>Detalles</td>
                <td>Editar</td>
            </tr>
            {%for v  in votaciones %}
            <tr class="contenidoTablas2">
                <td>{{v.nombre}}</td>
                {%if v.tipo_id is 1%}
                <td>Semestre</td>
                {%else%}
                <td>Facultad</td>
                {%endif%}
                <td>{{v.fechaInicio}}</td>
                <td>{{v.fechaFinal}}</td>
                <td> 2022-1 </td>
                <td>
                {%if v.estado_id is 1%}
                Postulacion
                {%elif v.estado_id is 2%}
                Votacion
                {%else%}
                Cerrada
                {%endif%}
                </td>
                <td>
                    {%if v.tipo_id is 1 %}
                    <!-- <h1>HOLA MUNDO</h1> -->
                    <form action="{%url 'app:vistaVotacionSemestrePost' v.id %}">
                        {% csrf_token %}
                        <button class="ojo">
                            <i class="fa-solid fa-eye"></i>
                        </button>
                    </form>
                    {%else%}
                    <!-- <h1>CHAO MUNDO</h1> -->
                    <form action="{%url 'app:vistaVotacionFacultadPost' v.id %}">
                        {% csrf_token %}
                        <button class="ojo">
                            <i class="fa-solid fa-eye"></i>
                        </button>
                    </form>
                    {%endif%}                    
                </td>
                <td>
                    <form action="{%url 'app:editarVotaciones' v.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit">
                            <i class="fa-solid fa-pencil"></i>
                        </button>
                    </form> 
                </td>
            </tr>
            {%endfor%}
        </table>
    </div>
</div>
{% endblock%} 

app/templates/app/menuDecano.html
{% extends "app/base.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/menu.css' %}" />
{% endblock%} 
    
{% block contenido%}    
        <div class="contenido">
            <table>
                <tr>
                    <td>
                        <a href="{%url 'app:agregarEstudiante'%}">
                            <button>
                                <i class="fa-solid fa-user-plus"></i>
                            </button>
                        </a>
                        <h3>Crear Estudiante</h3>
                    </td>
                    <td>
                        <a href="{%url 'app:listaDeEstudiantes'%}">
                            <button>
                                <i class="fa-solid fa-users"></i>
                            </button>
                        </a>
                        <h3>Lista de Estudiantes</h3>
                    </td>
                </tr>
                <tr>
                    <td>
                        <a href="{% url 'app:crearVotacion'%}">
                            <button>
                                <i class="fa-solid fa-circle-plus"></i>
                            </button>
                        </a>
                        <h3>Crear Votación</h3>
                    </td>
                    <td>
                        <a href="{% url 'app:listaDeVotaciones'%}">
                            <button>
                                <i class="fa-solid fa-list"></i>
                            </button>
                        </a>
                        <h3>Lista de Votaciones</h3>
                    </td>
                </tr>
            </table>
        </div>
{% endblock %}

app/templates/app/menuEstudiante.html
{% extends "app/headerEstudiante.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/menuEstudiante.css' %}" />
{% endblock%} 

{% block contenido%} 

        <div class="contenido">
            <a href="{% url 'app:listaVotacionesEstudiantes'%}">
                <button id="boton1">
                    <i class="fa-solid fa-list-ul">
                        <br>
                        <h2>Lista de Votaciones</h2>
                    </i>
                </button>
            </a>
            <a href="{% url 'app:postularme'%}">
                <button id="boton2">
                    <i class="fa-solid fa-user-plus">                  
                        <br>                    
                        <h2>Postularme</h2>
                    </i>
                </button>
            </a>
            <a href="{% url 'app:listaResultados'%}">
                <button id="boton3">
                    <i class="fa-solid fa-square-poll-horizontal">
                        <br>
                        <h2>Lista de Resultados</h2>
                    </i>
                </button>
            </a>
            
            <a href="{% url 'app:historicoVotaciones'%}">
                <button id="boton4">
                    <i class="fa-solid fa-clock-rotate-left">
                        <br>
                        <h2>Historico Votaciones</h2>
                    </i>
                </button>
            </a>    
            
        </div> 
    </div>
    
{% endblock %}

app/templates/app/postulacion.html
{% extends "app/headerEstudiante.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/postulacion.css' %}" />
{% endblock%} 

{% block contenido%} 
        
<div class="contenido">
    <form action="{% url 'app:postulacionPost' v.id%}" method="POST">
        {% csrf_token %} 
        <div class="formulario">
            <h2>Postulación</h2>
            <div class="votacion">
                <h3>Votación: <label>{{v.nombre}}</label></h3> 
            </div>
            <br>
            <div class="propuesta">
                <h3>Propuesta</h3>
                <textarea id="propuestaTXT" name="propuesta"  cols="60" rows="20"></textarea>
            </div>
        </div>    
        <Button id="botonPostularse">POSTULARSE</Button>                  
    </form>
    <form id="Bcancelar" action="{% url 'app:postularme'%}">
        {% csrf_token %} 
        <Button id="botonCancelar">CANCELAR</Button>
    </form>    

</div>
    
{% endblock%}

app/templates/app/postulacionEstudiante2.html
{% extends "app/base.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static 'app/css/tabla.css' %}" />
{% endblock%} 

{% block contenido %} 
<div class="contenido">
    <div class="titulo">
        <h1>Postulación de Estudiantes</h1>
    </div>
    <h3>Votación <label>Votación1</label></h3>
    <h3>Ciclo <label>2022-1</label></h3>
    <h4>Lista de Estudiantes</h4>
    <div>
        <table class="postulacion">
            <tr>
                <td><h2>Semestre</h2></td>
                <td><h2>Nombre</h2></td>
                <td><h2>Apellidos</h2></td>
                <td><h2>Postular</h2></td>
            </tr>
            <tr>
                <td>8</td>
                <td>Sebastian</td>
                <td>Meza Calle</td>
                <td><input type="radio"></td>
            </tr>
            <tr>
                <td>9</td>
                <td>Jennifer Andrea</td>
                <td>Camacho Manosalva</td>
                <td><input type="radio"></td>
            </tr>
        </table>
        <a href="{%url 'app:vistaVotacionFacultad'%}">
            <button id="botonpostular">Postular</button>
        </a>
    </div>
{% endblock%} 

app/templates/app/postularme.html
{% extends "app/headerEstudiante.html" %}
{% load static %}

{% block css%}   
<link rel="stylesheet" href="{% static 'app/css/listaVotaciones.css' %}" />
{% endblock%} 

{% block contenido%} 
        <div class="contenido">
             <h1>Lista de votaciones para postularse</h1>
             <p>En este listado encontrará todas las votaciones en las cuales podrá postularse</p>
             <div class="tabla">
                <table>
                    <tr class="TitulosTabla">
                        <td>Nombre</td>
                        <td>Tipo</td>
                        <td>Fecha de inicio</td>
                        <td>Fecha de finalización</td>
                        <td>Ciclo</td>
                        <td>Postularse</td>
                    </tr>
                    {%for v  in votaciones %}
                    <tr class="ContenidoTabla">
                        <td>{{v.nombre}}</td>
                        {%if v.tipo_id is 1%}
                        <td>Semestre</td>
                        {%else%}
                        <td>Facultad</td>
                        {%endif%}
                        <td>{{v.fechaInicio}}</td>
                        <td>{{v.fechaFinal}}</td>
                        <td>2022-1</td>              
                      
                        <td>
                            <form action="{% url 'app:postulacion' v.id %}">
                                {% csrf_token %}
                                <button class="ojo">
                                    <i class="fa-solid fa-user-plus"></i>
                                </button>
                            </form>
                        </td>
                     
                    </tr>
                    {%endfor%}
                </table>         
                
             </div>
        </div> 
    </div>
    
{% endblock%} 

app/templates/app/votarCandidato.html
{% extends "app/headerEstudiante.html" %}
{% load static %}

{% block css%} 
    <link rel="stylesheet" href="{% static 'app/css/votarCandidato.css' %}" />
{% endblock%} 

{% block contenido%} 
        
        <div class="contenido"> 
            <h1>{{v.nombre}}</h1> 
            {%if v.tipo_id is 1%}
            <h2>Semestre</h2>
            {%else%}
            <h2>Facultad</h2>
            {%endif%}
            <h3>Fecha de inicio <label>{{v.fechaInicio}}</label></h3>
            <br>
            <h3>Fecha de finalización <label>{{v.fechaFinal}}</label></h3>
            <br>
            <h3>Semestre <label>{{f}}</label></h3>

            <h4>Lista de candidatos</h4>
            {%for c in candidato%}
            <form action="{% url 'app:votacionExitosaPost' c.id %}" method="POST">
                <input type="text" name="Nombre">
                <div class="candidato"> 
                    {% csrf_token %}
                    <button>
                        <i class="fa-solid fa-user"></i>
                        <br>
                        <a href="">
                            <h3>Votar</h3>
                        </a>  
                    </button>
                    <ul>
                        <li>Nombre: {{c.estudiante.user.first_name}},{{c.estudiante.user.last_name}}</li>
                        <li>Propuesta: {{c.propuesta}}</li>    
                    </ul> 
                </div>
            </form>
            <br>
            <br>
            {%endfor%}                
        </div> 
        
    </div>
    {% endblock%}